### ISSUE TITLE
Uncaught SyntaxError: Unexpected token . in goldenlayout-base.css, internal require

### ISSUE THREAD

**Issue by measdot** [eddow/vue-golden-layout#16]
HI Eddow,

Could you please look into this?

```
import Vue from 'vue'
import vgl from 'vue-golden-layout'

Vue.use(vgl)
```

The Above line of codes throw me the below error:

> /Users/kumar/workspace/staff-vue/node_modules/golden-layout/src/css/goldenlayout-base.css:1 Uncaught SyntaxError: Unexpected token .
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object._b2fa.f.(anonymous function) (/Users/kumar/workspace/staff-vue/node_modules/vue-golden-layout/dist/vue-golden-layout.js:44:1)

I have satisfied the jquery dependenc.  
Webpack
``` 
new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery'
		})
```
main.js

`window.jQuery = window.$ = require('jquery/dist/jquery.min')`

**Comment by measdot** [comment]
I figured out this was due to the boilerplate I am using. It assumes we add 'vue-golden-library' package in White-listing Externals.

**Boilerplate Instructions**
https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals

**Affected source code**
https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L14-L21
