### ISSUE TITLE
Adjacent JSX

### ISSUE THREAD

**Issue by shiyafei** [eddow/vue-golden-layout#3]
when I run command: npm run compile, then error happen,and console no other print unless press CTRL + C to finsh process

> vue-golden-layout@1.0.7 compile /home/shiyafei/新建文件夹/temp/vue-golden-layout
> node fuse

→Typescript config:  /tsconfig.json
{ Error: Cannot find module 'vue-template-es2015-compiler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at VuePluginClass.transform (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/fuse-box/dist/commonjs/plugins/VuePlugin.js:36:29)
    at tasks.push (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/fuse-box/dist/commonjs/core/File.js:131:59)
    at context.queue.realm_utils_1.each.promise (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/fuse-box/dist/commonjs/core/File.js:135:76)
    at iterate (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/realm-utils/dist/commonjs/each.js:79:34)
    at /home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/realm-utils/dist/commonjs/each.js:92:16
    at Object.exports.Each [as each] (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/realm-utils/dist/commonjs/each.js:9:12) code: 'MODULE_NOT_FOUND' }

--------------------------
Bundle "vue-golden-layout" 

    index.js
    golden.js
    gl-roles.js
    gl-component.vue
    gl-group.js
└──  (5 files,  22.7 kB) vue-golden-layout
size: 22.7 kB in 740ms

  -------------- 

Launching quantum core
  → Generating abstraction, this may take a while
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (400:0)
    at Parser.pp$4.raise (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp.jsx_parseElementAt (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn-jsx/inject.js:349:12)
    at Parser.pp.jsx_parseElement (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn-jsx/inject.js:368:17)
    at Parser.parseExprAtom (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn-jsx/inject.js:390:23)
    at Parser.pp$3.parseExprSubscripts (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1932:17)
    at Parser.pp$3.parseMaybeUnary (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1923:26)
    at Parser.pp$3.parseExprOps (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/home/shiyafei/新建文件夹/temp/vue-golden-layout/node_modules/acorn/dist/acorn.js:1832:19)

**Comment by eddow** [comment]
Last correction are now tested and npm up-dated
